nginx:
    build: ./ngnix
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    mem_limit: 256m
    ports:
        - "80:80"
node1:
    build: ./node
    links:
        - redis
    mem_limit: 128m
    ports:
        - "8080"
node2:
    build: ./node
    links:
        - redis
    mem_limit: 128m
    ports:
        - "8080"
node3:
    build: ./node
    links:
        - redis
    mem_limit: 128m
    ports:
        - "8080"
redis:
    image: redis
    mem_limit: 128m
    ports:
        - "6379"
